# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Builds the debug code"
  lane :buildDebug do
    gradle(task: "bundleDebug")
  end

  desc "Builds the release code"
  lane :buildRelease do
    gradle(task: "bundleRelease")
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    upload_to_play_store(track: 'internal', aab: 'app/build/outputs/bundle/release/app-release.aab', mapping: 'app/build/outputs/mapping/release/mapping.txt')
  end

  desc "Submit a new Alpha Build to Play Store"
  lane :alpha do
    upload_to_play_store(track: 'alpha', aab: 'app/build/outputs/bundle/release/app-release.aab')
  end

  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    upload_to_play_store(track: 'beta', aab: 'app/build/outputs/bundle/release/app-release.aab')
  end

  desc "Submit a new Production Build to Play Store"
  lane :production do
    upload_to_play_store(track: 'production', aab: 'app/build/outputs/bundle/release/app-release.aab')
  end
end
